image: node:lts
pages:
  stage: deploy
  cache:
    key:
      files:
        - yarn.lock
      prefix: npm
    paths:
      - node_modules/
  script:
    - yarn
    - yarn build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
